
export const licenseTypesData = [
    { licenseName: 'ELECTRONIC SHOP', licenseCategory: 'TRADE', applicationForm: 'FORM.1', description: 'License to trade as an electronic shop' },
    { licenseName: 'GENERAL BUSINESS', licenseCategory: 'TRADE', applicationForm: 'FORM.1', description: 'General business trade license' },
    { licenseName: 'PLACE OF ENTERTAINMENT', licenseCategory: 'ENTERTAINMENT', applicationForm: 'FORM.1', description: 'License to keep a place of entertainment' },
    { licenseName: 'PHARMACY', licenseCategory: 'HEALTH', applicationForm: 'FORM.1', description: 'License to trade as pharmacy' },
    { licenseName: 'SECOND HAND USED CLOTHING', licenseCategory: 'TRADE', applicationForm: 'FORM.5', description: 'Second hand dealers license for used clothing' },
    { licenseName: 'FUEL DISTRIBUTION/INDUSTRIAL GAS', licenseCategory: 'FUEL', applicationForm: 'FORM.1', description: 'License to trade as fuel distribution/industrial gas' },
    { licenseName: 'MECHANICAL WORKSHOP', licenseCategory: 'INDUSTRIAL', applicationForm: 'FORM.1', description: 'License to trade as mechanical workshop' },
    { licenseName: 'MANUFACTURER', licenseCategory: 'INDUSTRIAL', applicationForm: 'FORM.1', description: 'License to trade as manufacturer' },
    { licenseName: 'FUEL STATION', licenseCategory: 'FUEL', applicationForm: 'FORM.1', description: 'License to trade as fuel station' },
    { licenseName: 'TAVERN', licenseCategory: 'LIQUOR', applicationForm: 'FORM 1', description: 'Liquor license - Tavern' },
    { licenseName: 'LIMITED HOTEL', licenseCategory: 'LIQUOR', applicationForm: 'FORM 1', description: 'Liquor license - Limited Hotel' },
    { licenseName: 'PACKET (LIQUOR)', licenseCategory: 'LIQUOR', applicationForm: 'FORM.5', description: 'Renewal of liquor license - Packet (sea vessels)' },
    { licenseName: 'PUBLICAN', licenseCategory: 'LIQUOR', applicationForm: 'FORM 1', description: 'Liquor license - Publican' },
    { licenseName: 'RESTAURANT', licenseCategory: 'LIQUOR', applicationForm: 'FORM 7', description: 'Liquor license - Restaurant' },
    { licenseName: 'STORE KEEPERS', licenseCategory: 'LIQUOR', applicationForm: 'FORM.3', description: 'Liquor license - Store Keepers' },
    { licenseName: 'BOOTH', licenseCategory: 'LIQUOR', applicationForm: 'FORM.4', description: 'Liquor license - Booth' },
    { licenseName: 'BOTTLE-SHOP', licenseCategory: 'LIQUOR', applicationForm: 'FORM 12', description: 'Liquor license - Bottle-Shop' },
    { licenseName: 'CANTEEN', licenseCategory: 'LIQUOR', applicationForm: 'FORM 12', description: 'Liquor license - Canteen' },
    { licenseName: 'CLUB', licenseCategory: 'LIQUOR', applicationForm: 'FORM 6', description: 'Liquor license - Club' },
    { licenseName: 'MOTOR VEHICLE DEALER', licenseCategory: 'TRADE', applicationForm: 'FORM.1', description: 'License to trade as motor vehicle dealer' },
    { licenseName: 'BARBER SHOP', licenseCategory: 'SERVICES', applicationForm: 'FORM.1', description: 'Barber shop license' }
];

export const checklistRequirementsData = [
    // ELECTRONIC SHOP
    { licenseName: 'ELECTRONIC SHOP', itemNumber: 1, documentName: 'Application FORM.1', responsibleEntity: 'NCDC', requirementNote: 'Completed form, signed and dated' },
    { licenseName: 'ELECTRONIC SHOP', itemNumber: 2, documentName: 'Physical Planning Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if land use changes' },
    { licenseName: 'ELECTRONIC SHOP', itemNumber: 3, documentName: 'Building Authority Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if structural changes occur' },
    { licenseName: 'ELECTRONIC SHOP', itemNumber: 4, documentName: 'Land Title/Lease Agreement or Consent letter', responsibleEntity: 'Landlord', requirementNote: 'Applicable if change of ownership or tenancy' },
    { licenseName: 'ELECTRONIC SHOP', itemNumber: 5, documentName: 'Radio communication Apparatus License', responsibleEntity: 'National Information and Technology Authority (NICTA)', requirementNote: 'Valid' },
    { licenseName: 'ELECTRONIC SHOP', itemNumber: 6, documentName: 'Certificate of Incorporation', responsibleEntity: 'IPA', requirementNote: 'Local & Foreign Companies' },
    { licenseName: 'ELECTRONIC SHOP', itemNumber: 7, documentName: 'Company Extract', responsibleEntity: 'IPA', requirementNote: 'Local & Foreign Companies' },
    { licenseName: 'ELECTRONIC SHOP', itemNumber: 8, documentName: 'Certificate of Registration of Business Name', responsibleEntity: 'IPA', requirementNote: 'Valid' },
    { licenseName: 'ELECTRONIC SHOP', itemNumber: 9, documentName: 'Certificate Permitting Foreigners to Operate Business in PNG', responsibleEntity: 'IPA', requirementNote: 'Applicable if foreign owned entity' },
    { licenseName: 'ELECTRONIC SHOP', itemNumber: 10, documentName: 'Land Tax & Garbage Rate', responsibleEntity: 'NCDC', requirementNote: 'Evidence of payment' },
    { licenseName: 'ELECTRONIC SHOP', itemNumber: 11, documentName: 'Copy of License for previous operator', responsibleEntity: 'Applicant', requirementNote: 'Application if COM' },

    // GENERAL BUSINESS
    { licenseName: 'GENERAL BUSINESS', itemNumber: 1, documentName: 'Application FORM .1', responsibleEntity: 'NCDC', requirementNote: 'Completed, signed and dated' },
    { licenseName: 'GENERAL BUSINESS', itemNumber: 2, documentName: 'Physical Planning Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if land use changes' },
    { licenseName: 'GENERAL BUSINESS', itemNumber: 3, documentName: 'Building Authority Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if structural changes occur' },
    { licenseName: 'GENERAL BUSINESS', itemNumber: 4, documentName: 'Land Title/Lease Agreement', responsibleEntity: 'Landlord', requirementNote: 'Valid' },
    { licenseName: 'GENERAL BUSINESS', itemNumber: 5, documentName: 'Certificate of Incorporation', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Companies' },
    { licenseName: 'GENERAL BUSINESS', itemNumber: 6, documentName: 'Company Extract', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Companies' },
    { licenseName: 'GENERAL BUSINESS', itemNumber: 7, documentName: 'Certificate of Registration of Business Name', responsibleEntity: 'IPA', requirementNote: 'Valid' },
    { licenseName: 'GENERAL BUSINESS', itemNumber: 8, documentName: 'Certificate Permitting Foreigners to Operate Business in PNG', responsibleEntity: 'IPA', requirementNote: 'Applicable for Foreign Enterprise' },
    { licenseName: 'GENERAL BUSINESS', itemNumber: 9, documentName: 'Land Tax & Garbage Rates', responsibleEntity: 'NCDC', requirementNote: 'Evidence of payment' },
    { licenseName: 'GENERAL BUSINESS', itemNumber: 10, documentName: 'Copy of License for previous Operator', responsibleEntity: 'Applicant', requirementNote: 'Applicable if COM/New Ownership' },

    // PLACE OF ENTERTAINMENT
    { licenseName: 'PLACE OF ENTERTAINMENT', itemNumber: 1, documentName: 'Application FORM.1 Reg:Sec.5(1)', responsibleEntity: 'NCDC', requirementNote: 'Completed, signed and dated' },
    { licenseName: 'PLACE OF ENTERTAINMENT', itemNumber: 2, documentName: 'Physical Planning Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if land use changes' },
    { licenseName: 'PLACE OF ENTERTAINMENT', itemNumber: 3, documentName: 'Building Authority Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if structural changes occur' },
    { licenseName: 'PLACE OF ENTERTAINMENT', itemNumber: 4, documentName: 'Land Title/Lease Agreement', responsibleEntity: 'Landlord', requirementNote: 'Valid' },
    { licenseName: 'PLACE OF ENTERTAINMENT', itemNumber: 5, documentName: 'Certificate of Incorporation', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Companies' },
    { licenseName: 'PLACE OF ENTERTAINMENT', itemNumber: 6, documentName: 'Company Extract', responsibleEntity: 'IPA', requirementNote: 'Local & Foreign Companies' },
    { licenseName: 'PLACE OF ENTERTAINMENT', itemNumber: 7, documentName: 'Certificate of Registration of Business Name', responsibleEntity: 'IPA', requirementNote: 'Valid' },
    { licenseName: 'PLACE OF ENTERTAINMENT', itemNumber: 8, documentName: 'Certificate Permitting Foreigners to Operate Business in PNG', responsibleEntity: 'IPA', requirementNote: 'Applicable for Foreign Enterprise' },
    { licenseName: 'PLACE OF ENTERTAINMENT', itemNumber: 9, documentName: 'Land Tax & Garbage Rate', responsibleEntity: 'NCDC-Revenue', requirementNote: 'Evidence of payment' },
    { licenseName: 'PLACE OF ENTERTAINMENT', itemNumber: 10, documentName: 'Copy of License for previous operator', responsibleEntity: 'Applicant', requirementNote: 'Applicable if COM/New Ownership' },

    // PHARMACY
    { licenseName: 'PHARMACY', itemNumber: 1, documentName: 'Application FORM.1', responsibleEntity: 'NCDC', requirementNote: 'Completed, signed and dated' },
    { licenseName: 'PHARMACY', itemNumber: 2, documentName: 'Physical Planning Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if land use changes' },
    { licenseName: 'PHARMACY', itemNumber: 3, documentName: 'Building Authority Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if structural changes occur' },
    { licenseName: 'PHARMACY', itemNumber: 4, documentName: 'Land Title/Lease Agreement', responsibleEntity: 'Landlord', requirementNote: 'Valid' },
    { licenseName: 'PHARMACY', itemNumber: 5, documentName: 'Pharmaceutical License', responsibleEntity: 'NDoH-Pharmacy Board', requirementNote: 'Valid' },
    { licenseName: 'PHARMACY', itemNumber: 6, documentName: 'Certificate of Incorporation', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Companies' },
    { licenseName: 'PHARMACY', itemNumber: 7, documentName: 'Company Extract', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Companies' },
    { licenseName: 'PHARMACY', itemNumber: 8, documentName: 'Certificate of Registration of Business Name', responsibleEntity: 'IPA', requirementNote: 'Valid' },
    { licenseName: 'PHARMACY', itemNumber: 9, documentName: 'Certificate Permitting Foreigners to Operate Business in PNG', responsibleEntity: 'IPA', requirementNote: 'Applicable for Foreign Enterprise' },
    { licenseName: 'PHARMACY', itemNumber: 10, documentName: 'Land Tax & Garbage Rate', responsibleEntity: 'NCDC', requirementNote: 'Evidence of payment' },
    { licenseName: 'PHARMACY', itemNumber: 11, documentName: 'Copy of License for previous operator', responsibleEntity: 'Applicant', requirementNote: 'Application if COM/New Ownership' },

    // SECOND HAND USED CLOTHING
    { licenseName: 'SECOND HAND USED CLOTHING', itemNumber: 1, documentName: 'Application FORM.5', responsibleEntity: 'NCDC', requirementNote: 'Completed, signed and dated' },
    { licenseName: 'SECOND HAND USED CLOTHING', itemNumber: 2, documentName: 'Certificate of Fumigation', responsibleEntity: 'National Department of Health (NDoH)', requirementNote: 'Valid' },
    { licenseName: 'SECOND HAND USED CLOTHING', itemNumber: 3, documentName: 'Physical Planning Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if land use changes' },
    { licenseName: 'SECOND HAND USED CLOTHING', itemNumber: 4, documentName: 'Building Authority Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if structural changes occur' },
    { licenseName: 'SECOND HAND USED CLOTHING', itemNumber: 5, documentName: 'Land Title/Lease Agreement', responsibleEntity: 'Landlord', requirementNote: 'Valid' },
    { licenseName: 'SECOND HAND USED CLOTHING', itemNumber: 6, documentName: 'Certificate of Incorporation', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Companies' },
    { licenseName: 'SECOND HAND USED CLOTHING', itemNumber: 7, documentName: 'Company Extract', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Companies' },
    { licenseName: 'SECOND HAND USED CLOTHING', itemNumber: 8, documentName: 'Certificate of Registration of Business Name', responsibleEntity: 'IPA', requirementNote: 'Valid' },
    { licenseName: 'SECOND HAND USED CLOTHING', itemNumber: 9, documentName: 'Certificate Permitting Foreigners to Operate Business in PNG', responsibleEntity: 'IPA', requirementNote: 'Applicable for foreign Enterprise' },
    { licenseName: 'SECOND HAND USED CLOTHING', itemNumber: 10, documentName: 'Land Tax & Garbage Rate', responsibleEntity: 'NCDC', requirementNote: 'Evidence of Payment' },
    { licenseName: 'SECOND HAND USED CLOTHING', itemNumber: 11, documentName: 'Copy of License for previous Operator', responsibleEntity: 'Applicant', requirementNote: 'Application if COM/New Ownership' },

    // FUEL DISTRIBUTION/INDUSTRIAL GAS
    { licenseName: 'FUEL DISTRIBUTION/INDUSTRIAL GAS', itemNumber: 1, documentName: 'Application FORM.1', responsibleEntity: 'NCDC', requirementNote: 'Completed form ,signed & dated' },
    { licenseName: 'FUEL DISTRIBUTION/INDUSTRIAL GAS', itemNumber: 2, documentName: 'Inflammable & Dangerous Goods License/certificate', responsibleEntity: 'Labour Department', requirementNote: 'Valid' },
    { licenseName: 'FUEL DISTRIBUTION/INDUSTRIAL GAS', itemNumber: 3, documentName: 'Physical Planning Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if land use changes occur' },
    { licenseName: 'FUEL DISTRIBUTION/INDUSTRIAL GAS', itemNumber: 4, documentName: 'Building Authority Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if structural changes occur' },
    { licenseName: 'FUEL DISTRIBUTION/INDUSTRIAL GAS', itemNumber: 5, documentName: 'Land Title/Lease Agreement or Consent letter', responsibleEntity: 'Landlord', requirementNote: 'Valid Lease' },
    { licenseName: 'FUEL DISTRIBUTION/INDUSTRIAL GAS', itemNumber: 6, documentName: 'Certificate of Incorporation', responsibleEntity: 'IPA', requirementNote: 'Local & Foreign Enterprise' },
    { licenseName: 'FUEL DISTRIBUTION/INDUSTRIAL GAS', itemNumber: 7, documentName: 'Company Extract', responsibleEntity: 'IPA', requirementNote: 'Local & Foreign Enterprise' },
    { licenseName: 'FUEL DISTRIBUTION/INDUSTRIAL GAS', itemNumber: 8, documentName: 'Certificate of Registration of Business Name', responsibleEntity: 'IPA', requirementNote: 'Valid' },
    { licenseName: 'FUEL DISTRIBUTION/INDUSTRIAL GAS', itemNumber: 9, documentName: 'Certificate Permitting Foreigners to Operate Business in PNG', responsibleEntity: 'IPA', requirementNote: 'Applicable if foreign owned entity' },
    { licenseName: 'FUEL DISTRIBUTION/INDUSTRIAL GAS', itemNumber: 10, documentName: 'Land Tax & Garbage Rate', responsibleEntity: 'NCDC', requirementNote: 'Evidence of payment' },
    { licenseName: 'FUEL DISTRIBUTION/INDUSTRIAL GAS', itemNumber: 11, documentName: 'Copy of License for previous operator', responsibleEntity: 'Applicant', requirementNote: 'Application if COM' },

    // MECHANICAL WORKSHOP
    { licenseName: 'MECHANICAL WORKSHOP', itemNumber: 1, documentName: 'Application FORM.1', responsibleEntity: 'NCDC', requirementNote: 'Completed, signed and dated' },
    { licenseName: 'MECHANICAL WORKSHOP', itemNumber: 2, documentName: 'Physical Planning Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if land use changes' },
    { licenseName: 'MECHANICAL WORKSHOP', itemNumber: 3, documentName: 'Building Authority Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if structural changes occur' },
    { licenseName: 'MECHANICAL WORKSHOP', itemNumber: 4, documentName: 'Land Title/Lease Agreement', responsibleEntity: 'Landlord', requirementNote: 'Valid' },
    { licenseName: 'MECHANICAL WORKSHOP', itemNumber: 5, documentName: 'Factory/Manufacturer License', responsibleEntity: 'Labour Department', requirementNote: 'Valid' },
    { licenseName: 'MECHANICAL WORKSHOP', itemNumber: 6, documentName: 'Certificate of Incorporation', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Companies' },
    { licenseName: 'MECHANICAL WORKSHOP', itemNumber: 7, documentName: 'Company Extract', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Companies' },
    { licenseName: 'MECHANICAL WORKSHOP', itemNumber: 8, documentName: 'Certificate of Registration of Business Name', responsibleEntity: 'IPA', requirementNote: 'Valid' },
    { licenseName: 'MECHANICAL WORKSHOP', itemNumber: 9, documentName: 'Certificate Permitting Foreigners to Operate Business in PNG', responsibleEntity: 'IPA', requirementNote: 'Applicable for foreign Enterprise' },
    { licenseName: 'MECHANICAL WORKSHOP', itemNumber: 10, documentName: 'Land Tax & Garbage Rate', responsibleEntity: 'NCDC', requirementNote: 'Evidence of payment' },
    { licenseName: 'MECHANICAL WORKSHOP', itemNumber: 11, documentName: 'Copy of license for the previous operator', responsibleEntity: 'Applicant', requirementNote: 'Application if COM/New Ownership' },

    // MANUFACTURER
    { licenseName: 'MANUFACTURER', itemNumber: 1, documentName: 'Application FORM.1', responsibleEntity: 'NCDC', requirementNote: 'Completed, signed and dated' },
    { licenseName: 'MANUFACTURER', itemNumber: 2, documentName: 'Physical Planning Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if land use changes' },
    { licenseName: 'MANUFACTURER', itemNumber: 3, documentName: 'Building Authority Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if structural changes occur' },
    { licenseName: 'MANUFACTURER', itemNumber: 4, documentName: 'Land Title/Lease Agreement', responsibleEntity: 'Landlord', requirementNote: 'Valid' },
    { licenseName: 'MANUFACTURER', itemNumber: 5, documentName: 'Food Safety Management System (HACCP)', responsibleEntity: 'Applicant', requirementNote: 'Applicable for Food Manufacturers' },
    { licenseName: 'MANUFACTURER', itemNumber: 6, documentName: 'Factory/Manufacturer License', responsibleEntity: 'Labour Department', requirementNote: 'Valid' },
    { licenseName: 'MANUFACTURER', itemNumber: 7, documentName: 'Certificate of Incorporation', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Companies' },
    { licenseName: 'MANUFACTURER', itemNumber: 8, documentName: 'Company Extract', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Companies' },
    { licenseName: 'MANUFACTURER', itemNumber: 9, documentName: 'Certificate of Registration of Business Name', responsibleEntity: 'IPA', requirementNote: 'Valid' },
    { licenseName: 'MANUFACTURER', itemNumber: 10, documentName: 'Certificate Permitting Foreigners to Operate Business in PNG', responsibleEntity: 'IPA', requirementNote: 'Applicable for foreign Enterprise' },
    { licenseName: 'MANUFACTURER', itemNumber: 11, documentName: 'Land Tax & Garbage Rate', responsibleEntity: 'NCDC', requirementNote: 'Evidence of payment' },
    { licenseName: 'MANUFACTURER', itemNumber: 12, documentName: 'Copy of License for previous operator', responsibleEntity: 'Applicant', requirementNote: 'Applicable if COM/New Ownership' },

    // FUEL STATION
    { licenseName: 'FUEL STATION', itemNumber: 1, documentName: 'Application FORM.1', responsibleEntity: 'NCDC', requirementNote: 'Completed, signed and dated' },
    { licenseName: 'FUEL STATION', itemNumber: 2, documentName: 'Inflammable & Dangerous Goods License/certificate', responsibleEntity: 'Labour Department', requirementNote: 'Valid' },
    { licenseName: 'FUEL STATION', itemNumber: 3, documentName: 'Physical Planning Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if land use changes' },
    { licenseName: 'FUEL STATION', itemNumber: 4, documentName: 'Building Authority Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if structural changes occur' },
    { licenseName: 'FUEL STATION', itemNumber: 5, documentName: 'Land Title/Lease Agreement', responsibleEntity: 'Landlord', requirementNote: 'Valid' },
    { licenseName: 'FUEL STATION', itemNumber: 6, documentName: 'Certificate of Incorporation', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Companies' },
    { licenseName: 'FUEL STATION', itemNumber: 7, documentName: 'Company Extract', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Companies' },
    { licenseName: 'FUEL STATION', itemNumber: 8, documentName: 'Certificate of Registration of Business Name', responsibleEntity: 'IPA', requirementNote: 'Valid' },
    { licenseName: 'FUEL STATION', itemNumber: 9, documentName: 'Certificate Permitting Foreigners to Operate Business in PNG', responsibleEntity: 'IPA', requirementNote: 'Applicable for foreign Enterprise' },
    { licenseName: 'FUEL STATION', itemNumber: 10, documentName: 'Land Tax & Garbage Rate', responsibleEntity: 'NCDC', requirementNote: 'Evidence of payment' },
    { licenseName: 'FUEL STATION', itemNumber: 11, documentName: 'Copy of License for previous operator', responsibleEntity: 'Applicant', requirementNote: 'Applicable if COM/New Ownership' },

    // TAVERN
    { licenseName: 'TAVERN', itemNumber: 1, documentName: 'Application FORM 1', responsibleEntity: 'NCDC', requirementNote: 'Completed, dated and signed' },
    { licenseName: 'TAVERN', itemNumber: 2, documentName: 'Physical planning Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if Land Use Changes' },
    { licenseName: 'TAVERN', itemNumber: 3, documentName: 'Building Authority Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if structural changes occur' },
    { licenseName: 'TAVERN', itemNumber: 4, documentName: 'Land title or Lease Agreement', responsibleEntity: 'Landlord', requirementNote: 'Valid' },
    { licenseName: 'TAVERN', itemNumber: 5, documentName: 'Certificate of Incorporation', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Enterprises' },
    { licenseName: 'TAVERN', itemNumber: 6, documentName: 'Foreign Enterprise Certificate', responsibleEntity: 'IPA', requirementNote: 'Applicable if Foreign Enterprise' },
    { licenseName: 'TAVERN', itemNumber: 7, documentName: 'Company Extract', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Enterprise' },
    { licenseName: 'TAVERN', itemNumber: 8, documentName: 'Business Name Registration Certificate', responsibleEntity: 'IPA', requirementNote: 'Valid' },
    { licenseName: 'TAVERN', itemNumber: 9, documentName: 'Food Safety Management System (HACCP)', responsibleEntity: 'Applicant', requirementNote: 'Applicable if Food is served (Hazard Analysis Critical Control Point' },
    { licenseName: 'TAVERN', itemNumber: 10, documentName: 'Copy of License of Previous Operator', responsibleEntity: 'Applicant', requirementNote: 'Applicable if Change of Management occur' },
    { licenseName: 'TAVERN', itemNumber: 11, documentName: 'Number of Bars', responsibleEntity: 'Applicant', requirementNote: 'Name(s) of Bars to be identified by way of letter' },
    { licenseName: 'TAVERN', itemNumber: 12, documentName: 'Name of Approved Manager of the premise', responsibleEntity: 'Applicant', requirementNote: 'To be identified by way of letter' },
    { licenseName: 'TAVERN', itemNumber: 13, documentName: 'Statutory Declaration', responsibleEntity: 'Justice of Peace', requirementNote: 'Declaring all information, Materials are true and correct in nature' },
    { licenseName: 'TAVERN', itemNumber: 14, documentName: 'Land Tax & Garbage Bills', responsibleEntity: 'NCDC', requirementNote: 'Evidence of Payments' },

    // LIMITED HOTEL
    { licenseName: 'LIMITED HOTEL', itemNumber: 1, documentName: 'Application FORM 1', responsibleEntity: 'NCDC', requirementNote: 'Completed, dated and signed' },
    { licenseName: 'LIMITED HOTEL', itemNumber: 2, documentName: 'Physical planning Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if Land Use Changes' },
    { licenseName: 'LIMITED HOTEL', itemNumber: 3, documentName: 'Building Authority Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if structural changes occurs' },
    { licenseName: 'LIMITED HOTEL', itemNumber: 4, documentName: 'Land title or Lease Agreement', responsibleEntity: 'Landlord', requirementNote: 'Valid' },
    { licenseName: 'LIMITED HOTEL', itemNumber: 5, documentName: 'Certificate of Incorporation', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Enterprises' },
    { licenseName: 'LIMITED HOTEL', itemNumber: 6, documentName: 'Foreign Enterprise Certificate', responsibleEntity: 'IPA', requirementNote: 'Applicable if Foreign Enterprise' },
    { licenseName: 'LIMITED HOTEL', itemNumber: 7, documentName: 'Company Extract', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Enterprise' },
    { licenseName: 'LIMITED HOTEL', itemNumber: 8, documentName: 'Business Name Registration Certificate', responsibleEntity: 'IPA', requirementNote: 'Valid' },
    { licenseName: 'LIMITED HOTEL', itemNumber: 9, documentName: 'Food Safety Management System', responsibleEntity: 'Applicant', requirementNote: 'Applicable if Food is served. Hazard Analysis Critical Control Point (HACCP)' },
    { licenseName: 'LIMITED HOTEL', itemNumber: 10, documentName: 'Copy of License of Previous Operator', responsibleEntity: 'Applicant', requirementNote: 'Applicable if Change of Management occurs' },
    { licenseName: 'LIMITED HOTEL', itemNumber: 11, documentName: 'Number of Bars', responsibleEntity: 'Applicant', requirementNote: 'Name(s) of Bars to be identified by way of letter' },
    { licenseName: 'LIMITED HOTEL', itemNumber: 12, documentName: 'Name of Approved Manager of the premise', responsibleEntity: 'Applicant', requirementNote: 'To be identified by way of letter' },
    { licenseName: 'LIMITED HOTEL', itemNumber: 13, documentName: 'Statutory Declaration', responsibleEntity: 'Justice of Peace', requirementNote: 'Declaring all information, Materials are true and correct in nature' },
    { licenseName: 'LIMITED HOTEL', itemNumber: 14, documentName: 'Land Tax & Garbage Bills', responsibleEntity: 'NCDC', requirementNote: 'Evidence' },

    // PACKET (LIQUOR)
    { licenseName: 'PACKET (LIQUOR)', itemNumber: 1, documentName: 'Application Form No.5', responsibleEntity: 'NCDC', requirementNote: 'Completed, signed and dated' },
    { licenseName: 'PACKET (LIQUOR)', itemNumber: 2, documentName: 'Certificate Business Name Registration', responsibleEntity: 'IPA', requirementNote: 'Valid' },
    { licenseName: 'PACKET (LIQUOR)', itemNumber: 3, documentName: 'Certified Sea Going Vessel', responsibleEntity: 'National Maritime Safety Authority', requirementNote: 'Safety' },
    { licenseName: 'PACKET (LIQUOR)', itemNumber: 4, documentName: 'Certified Overseas Ship', responsibleEntity: 'National Maritime Safety Authority', requirementNote: 'Safety' },
    { licenseName: 'PACKET (LIQUOR)', itemNumber: 5, documentName: 'Name of Master /Captain of Vessel/ship', responsibleEntity: 'Applicant', requirementNote: 'To be confirmed by way of Letter' },
    { licenseName: 'PACKET (LIQUOR)', itemNumber: 6, documentName: 'Statutory Declaration Form', responsibleEntity: 'Justice of Peace', requirementNote: 'All information, material particular are true and correct' },

    // RESTAURANT
    { licenseName: 'RESTAURANT', itemNumber: 1, documentName: 'Application FORM 7', responsibleEntity: 'NCDC', requirementNote: 'Completed, dated and signed' },
    { licenseName: 'RESTAURANT', itemNumber: 2, documentName: 'Physical planning Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if Land Use Changes' },
    { licenseName: 'RESTAURANT', itemNumber: 3, documentName: 'Building Authority Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if structural changes occur' },
    { licenseName: 'RESTAURANT', itemNumber: 4, documentName: 'Land title or Lease Agreement', responsibleEntity: 'LandLord', requirementNote: 'Valid' },
    { licenseName: 'RESTAURANT', itemNumber: 5, documentName: 'Certificate of Incorporation', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Enterprises' },
    { licenseName: 'RESTAURANT', itemNumber: 6, documentName: 'Certificate Permitting Foreigners to Operate Business in PNG', responsibleEntity: 'IPA', requirementNote: 'Applicable if Foreign Enterprise' },
    { licenseName: 'RESTAURANT', itemNumber: 7, documentName: 'Company Extract', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Enterprises' },
    { licenseName: 'RESTAURANT', itemNumber: 8, documentName: 'Business Name Registration Certificate', responsibleEntity: 'IPA', requirementNote: 'Valid' },
    { licenseName: 'RESTAURANT', itemNumber: 9, documentName: 'Food Safety Management System (HACCP)', responsibleEntity: 'Applicant', requirementNote: 'Hazard Analysis Critical Control Point (HACCP)' },
    { licenseName: 'RESTAURANT', itemNumber: 10, documentName: 'Copy of license for previous operator', responsibleEntity: 'Applicant', requirementNote: 'Applicable if Change of Management' },
    { licenseName: 'RESTAURANT', itemNumber: 11, documentName: 'Number of Bars', responsibleEntity: 'Applicant', requirementNote: 'Name of bar (s) to be identified by way of letter' },
    { licenseName: 'RESTAURANT', itemNumber: 12, documentName: 'Name of Approved Manager of the premise', responsibleEntity: 'Applicant', requirementNote: 'Name of Manager (s) to be identified by way of letter' },
    { licenseName: 'RESTAURANT', itemNumber: 13, documentName: 'Statutory Declaration', responsibleEntity: 'Justice of Peace', requirementNote: 'Declaring all information, Materials are true and correct in nature' },
    { licenseName: 'RESTAURANT', itemNumber: 14, documentName: 'Land Tax & Garbage Bills', responsibleEntity: 'NCDC', requirementNote: 'Evidence of payment' },

    // BOTTLE-SHOP
    { licenseName: 'BOTTLE-SHOP', itemNumber: 1, documentName: 'Application Form No 12', responsibleEntity: 'NCDC', requirementNote: 'Completed, dated & signed' },
    { licenseName: 'BOTTLE-SHOP', itemNumber: 2, documentName: 'Physical planning Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if Land Use Changes' },
    { licenseName: 'BOTTLE-SHOP', itemNumber: 3, documentName: 'Building Authority Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if structural changes occur' },
    { licenseName: 'BOTTLE-SHOP', itemNumber: 4, documentName: 'Land title or Lease Agreement', responsibleEntity: 'LandLord', requirementNote: 'Valid' },
    { licenseName: 'BOTTLE-SHOP', itemNumber: 5, documentName: 'Certificate of Incorporation', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign' },
    { licenseName: 'BOTTLE-SHOP', itemNumber: 6, documentName: 'Certificate Permitting Foreigners to Operate Business in PNG', responsibleEntity: 'IPA', requirementNote: 'Applicable if Foreign Enterprise' },
    { licenseName: 'BOTTLE-SHOP', itemNumber: 7, documentName: 'Company Extract', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Enterprises' },
    { licenseName: 'BOTTLE-SHOP', itemNumber: 8, documentName: 'Business Name Registration Certificate', responsibleEntity: 'IPA', requirementNote: 'Valid' },
    { licenseName: 'BOTTLE-SHOP', itemNumber: 9, documentName: 'Name of Approved Manager of the Premise', responsibleEntity: 'Applicant', requirementNote: 'To be identified by way of letter' },
    { licenseName: 'BOTTLE-SHOP', itemNumber: 10, documentName: 'Statutory Declaration', responsibleEntity: 'Justice of Peace', requirementNote: 'All information, Materials are true and correct in nature' },
    { licenseName: 'BOTTLE-SHOP', itemNumber: 11, documentName: 'Copy of License of Previous Operator', responsibleEntity: 'Applicant', requirementNote: 'Applicable if Change of Management' },
    { licenseName: 'BOTTLE-SHOP', itemNumber: 12, documentName: 'Land Tax and Garbage Bills', responsibleEntity: 'NCDC', requirementNote: 'Evidence' },

    // CANTEEN
    { licenseName: 'CANTEEN', itemNumber: 1, documentName: 'Application FORM No.12', responsibleEntity: 'NCDC', requirementNote: 'Completed, signed and dated' },
    { licenseName: 'CANTEEN', itemNumber: 2, documentName: 'Physical planning Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if change in Land Use occur' },
    { licenseName: 'CANTEEN', itemNumber: 3, documentName: 'Building Authority Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if structural changes occur' },
    { licenseName: 'CANTEEN', itemNumber: 4, documentName: 'Land Title or Lease Agreement', responsibleEntity: 'LandLord', requirementNote: 'Valid' },
    { licenseName: 'CANTEEN', itemNumber: 5, documentName: 'Certificate of Incorporation', responsibleEntity: 'IPA', requirementNote: 'Valid' },
    { licenseName: 'CANTEEN', itemNumber: 6, documentName: 'Business Name Registration Certificate', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Enterprise' },
    { licenseName: 'CANTEEN', itemNumber: 7, documentName: 'Certificate Permitting Foreigners to Operate Business in PNG', responsibleEntity: 'IPA', requirementNote: 'Applicable if Foreign Enterprises' },
    { licenseName: 'CANTEEN', itemNumber: 8, documentName: 'Company Extract', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Enterprise' },
    { licenseName: 'CANTEEN', itemNumber: 9, documentName: 'Copy of License for the Previous Operator', responsibleEntity: 'Applicant', requirementNote: 'Applicable if change of Management occurs' },
    { licenseName: 'CANTEEN', itemNumber: 10, documentName: "Canteen's Rules", responsibleEntity: 'Applicant', requirementNote: 'Updated Operational Orders/Rules' },
    { licenseName: 'CANTEEN', itemNumber: 11, documentName: 'List of number of Employees', responsibleEntity: 'Applicant', requirementNote: 'Updated List with Minimum of 25 heads' },
    { licenseName: 'CANTEEN', itemNumber: 12, documentName: 'Food Safety Management System (HACCP)', responsibleEntity: 'Applicant', requirementNote: 'Applicable If food is involved. Hazard Analysis Critical Control Point' },
    { licenseName: 'CANTEEN', itemNumber: 13, documentName: 'Name of Approved Licensee', responsibleEntity: 'Applicant', requirementNote: 'To be identified by way of letter' },
    { licenseName: 'CANTEEN', itemNumber: 14, documentName: 'Statutory Declaration Form', responsibleEntity: 'Justice of Peace', requirementNote: 'All information, Materials are true and correct in nature' },
    { licenseName: 'CANTEEN', itemNumber: 15, documentName: 'Land Tax & Garbage Bills', responsibleEntity: 'NCDC', requirementNote: 'Evidence' },

    // CLUB
    { licenseName: 'CLUB', itemNumber: 1, documentName: 'Application Form 6', responsibleEntity: 'NCDC', requirementNote: 'Completed, signed and dated' },
    { licenseName: 'CLUB', itemNumber: 2, documentName: 'Physical planning Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if Land Use Changes' },
    { licenseName: 'CLUB', itemNumber: 3, documentName: 'Building Authority Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if structural changes occur' },
    { licenseName: 'CLUB', itemNumber: 4, documentName: 'Land title or Lease Agreement', responsibleEntity: 'LandLord', requirementNote: 'Valid' },
    { licenseName: 'CLUB', itemNumber: 5, documentName: 'Certificate of Incorporation', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Enterprise' },
    { licenseName: 'CLUB', itemNumber: 6, documentName: 'Foreign Enterprise Certificate', responsibleEntity: 'IPA', requirementNote: 'Applicable if Foreign Enterprise' },
    { licenseName: 'CLUB', itemNumber: 7, documentName: 'Business Name Registration Certificate', responsibleEntity: 'IPA', requirementNote: 'Valid' },
    { licenseName: 'CLUB', itemNumber: 8, documentName: 'Food Safety Management System', responsibleEntity: 'Applicant', requirementNote: 'Applicable if food is involved' },
    { licenseName: 'CLUB', itemNumber: 9, documentName: 'Number of Bars', responsibleEntity: 'Applicant', requirementNote: 'Name(s) of Bars to be identified by way of letter' },
    { licenseName: 'CLUB', itemNumber: 10, documentName: 'Name of Approved Manager of the premise', responsibleEntity: 'Applicant', requirementNote: 'Valid' },
    { licenseName: 'CLUB', itemNumber: 11, documentName: 'Club Constitution/Rules', responsibleEntity: 'Applicant', requirementNote: 'Valid' },
    { licenseName: 'CLUB', itemNumber: 12, documentName: 'List of Subscribing Members', responsibleEntity: 'Applicant', requirementNote: 'In excess of 50 members' },
    { licenseName: 'CLUB', itemNumber: 13, documentName: 'Copy of the Annual General Meeting Minutes (AGM)', responsibleEntity: 'Applicant', requirementNote: 'Valid' },
    { licenseName: 'CLUB', itemNumber: 14, documentName: 'Copy of license of Previous Operator', responsibleEntity: 'Applicant', requirementNote: 'Applicable if Change of Management (COM)' },
    { licenseName: 'CLUB', itemNumber: 15, documentName: 'Statutory Declaration', responsibleEntity: 'Justice of Peace', requirementNote: 'All information, Materials are true and correct in nature' },
    { licenseName: 'CLUB', itemNumber: 16, documentName: 'Land Tax & Garbage Bills', responsibleEntity: 'NCDC', requirementNote: 'Evidence of payment' },

    // MOTOR VEHICLE DEALER
    { licenseName: 'MOTOR VEHICLE DEALER', itemNumber: 1, documentName: 'Application FORM.1', responsibleEntity: 'NCDC', requirementNote: 'Completed, signed and dated' },
    { licenseName: 'MOTOR VEHICLE DEALER', itemNumber: 2, documentName: 'Physical Planning Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if land use changes' },
    { licenseName: 'MOTOR VEHICLE DEALER', itemNumber: 3, documentName: 'Building Authority Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if structural changes occur' },
    { licenseName: 'MOTOR VEHICLE DEALER', itemNumber: 4, documentName: 'Land Title/Lease Agreement', responsibleEntity: 'Landlord', requirementNote: 'Valid' },
    { licenseName: 'MOTOR VEHICLE DEALER', itemNumber: 5, documentName: 'Motor Car Dealers License', responsibleEntity: 'Land Transport Board', requirementNote: 'Valid' },
    { licenseName: 'MOTOR VEHICLE DEALER', itemNumber: 6, documentName: 'Certificate of Incorporation', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Company' },
    { licenseName: 'MOTOR VEHICLE DEALER', itemNumber: 7, documentName: 'Company Extract', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Company' },
    { licenseName: 'MOTOR VEHICLE DEALER', itemNumber: 8, documentName: 'Certificate of Registration of Business Name', responsibleEntity: 'IPA', requirementNote: 'Valid' },
    { licenseName: 'MOTOR VEHICLE DEALER', itemNumber: 9, documentName: 'Certificate Permitting Foreigners to Operate Business in PNG', responsibleEntity: 'IPA', requirementNote: 'Applicable for foreign Enterprise' },
    { licenseName: 'MOTOR VEHICLE DEALER', itemNumber: 10, documentName: 'Land Tax & Garbage Rate', responsibleEntity: 'NCDC', requirementNote: 'Evidence of payment' },
    { licenseName: 'MOTOR VEHICLE DEALER', itemNumber: 11, documentName: 'Copy of License for previous operator', responsibleEntity: 'Applicant', requirementNote: 'Application if COM/New Ownership' },

    // BARBER SHOP
    { licenseName: 'BARBER SHOP', itemNumber: 1, documentName: 'Application FORM.1 Reg:3(2)', responsibleEntity: 'NCDC', requirementNote: 'Completed, signed and dated' },
    { licenseName: 'BARBER SHOP', itemNumber: 2, documentName: 'Physical Planning Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if land use changes' },
    { licenseName: 'BARBER SHOP', itemNumber: 3, documentName: 'Building Authority Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if structural changes occur' },
    { licenseName: 'BARBER SHOP', itemNumber: 4, documentName: 'Land Title/Lease Agreement', responsibleEntity: 'Landlord', requirementNote: 'Valid' },
    { licenseName: 'BARBER SHOP', itemNumber: 5, documentName: 'Certificate of Incorporation', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Companies' },
    { licenseName: 'BARBER SHOP', itemNumber: 6, documentName: 'Company Extract', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Companies' },
    { licenseName: 'BARBER SHOP', itemNumber: 7, documentName: 'Certificate of Registration of Business Name', responsibleEntity: 'IPA', requirementNote: 'Valid' },
    { licenseName: 'BARBER SHOP', itemNumber: 8, documentName: 'Certificate Permitting Foreigners to Operate Business in PNG', responsibleEntity: 'IPA', requirementNote: 'Applicable for foreign Enterprise' },
    { licenseName: 'BARBER SHOP', itemNumber: 9, documentName: 'Land Tax & Garbage Rate', responsibleEntity: 'NCDC', requirementNote: 'Evidence of payment' },
    { licenseName: 'BARBER SHOP', itemNumber: 10, documentName: 'Copy of license for previous Operator', responsibleEntity: 'Applicant', requirementNote: 'Application if COM/New Ownership' },

    // PUBLICAN
    { licenseName: 'PUBLICAN', itemNumber: 1, documentName: 'Application FORM 1', responsibleEntity: 'NCDC', requirementNote: 'Completed, dated and signed' },
    { licenseName: 'PUBLICAN', itemNumber: 2, documentName: 'Physical planning Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if Land Use Changes' },
    { licenseName: 'PUBLICAN', itemNumber: 3, documentName: 'Building Authority Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if structural changes occurs' },
    { licenseName: 'PUBLICAN', itemNumber: 4, documentName: 'Land title or Lease Agreement', responsibleEntity: 'Landlord', requirementNote: 'Valid' },
    { licenseName: 'PUBLICAN', itemNumber: 5, documentName: 'Certificate of Incorporation', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Enterprises' },
    { licenseName: 'PUBLICAN', itemNumber: 6, documentName: 'Foreign Enterprise Certificate', responsibleEntity: 'IPA', requirementNote: 'Applicable if Foreign Enterprise' },
    { licenseName: 'PUBLICAN', itemNumber: 7, documentName: 'Company Extract', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Enterprise' },
    { licenseName: 'PUBLICAN', itemNumber: 8, documentName: 'Business Name Registration Certificate', responsibleEntity: 'IPA', requirementNote: 'Valid' },
    { licenseName: 'PUBLICAN', itemNumber: 9, documentName: 'Food Safety Management System', responsibleEntity: 'Applicant', requirementNote: 'Applicable if Food is served. Hazard Analysis Critical Control Point (HACCP)' },
    { licenseName: 'PUBLICAN', itemNumber: 10, documentName: 'Copy of License of Previous Operator', responsibleEntity: 'Applicant', requirementNote: 'Applicable if Change of Management occurs' },
    { licenseName: 'PUBLICAN', itemNumber: 11, documentName: 'Number of Bars', responsibleEntity: 'Applicant', requirementNote: 'Name(s) of Bars to be identified by way of letter' },
    { licenseName: 'PUBLICAN', itemNumber: 12, documentName: 'Name of Approved Manager of the premise', responsibleEntity: 'Applicant', requirementNote: 'To be identified by way of letter' },
    { licenseName: 'PUBLICAN', itemNumber: 13, documentName: 'Statutory Declaration', responsibleEntity: 'Justice of Peace', requirementNote: 'Declaring all information, Materials are true and correct in nature' },
    { licenseName: 'PUBLICAN', itemNumber: 14, documentName: 'Land Tax & Garbage Bills', responsibleEntity: 'NCDC', requirementNote: 'Evidence' },

    // STORE KEEPERS
    { licenseName: 'STORE KEEPERS', itemNumber: 1, documentName: 'Completed application Form No. 3', responsibleEntity: 'NCDC', requirementNote: 'Completed, dated & signed' },
    { licenseName: 'STORE KEEPERS', itemNumber: 2, documentName: 'Physical planning Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if Land Use Changes occur' },
    { licenseName: 'STORE KEEPERS', itemNumber: 3, documentName: 'Building Authority Approvals', responsibleEntity: 'NCDC', requirementNote: 'Applicable if structural changes occur' },
    { licenseName: 'STORE KEEPERS', itemNumber: 4, documentName: 'Land title or Lease Agreement', responsibleEntity: 'IPA', requirementNote: 'Valid' },
    { licenseName: 'STORE KEEPERS', itemNumber: 5, documentName: 'Certificate of Incorporation', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Enterprises' },
    { licenseName: 'STORE KEEPERS', itemNumber: 6, documentName: 'Certificate Permitting Foreigners to Operate Business in PNG', responsibleEntity: 'IPA', requirementNote: 'Applicable if Foreign Enterprise' },
    { licenseName: 'STORE KEEPERS', itemNumber: 7, documentName: 'Business Name Registration Certificate', responsibleEntity: 'IPA', requirementNote: 'Valid' },
    { licenseName: 'STORE KEEPERS', itemNumber: 8, documentName: 'Company Extract', responsibleEntity: 'IPA', requirementNote: 'Local and Foreign Enterprise' },
    { licenseName: 'STORE KEEPERS', itemNumber: 9, documentName: 'Name of Approved Manager of the Premise', responsibleEntity: 'Applicant', requirementNote: 'To be identified by way of writing to NCDC' },
    { licenseName: 'STORE KEEPERS', itemNumber: 10, documentName: 'Statutory Declaration', responsibleEntity: 'Justice of Peace', requirementNote: 'Declaring all information, Materials are true and correct in nature' },
    { licenseName: 'STORE KEEPERS', itemNumber: 11, documentName: 'Copy of License for previous year', responsibleEntity: 'Applicant', requirementNote: 'Applicable if Change of Management' },
    { licenseName: 'STORE KEEPERS', itemNumber: 12, documentName: 'Land & Garbage Taxes', responsibleEntity: 'NCDC', requirementNote: 'Evidence' },

    // BOOTH
    { licenseName: 'BOOTH', itemNumber: 1, documentName: 'Complete Application Form No.4', responsibleEntity: 'NCDC', requirementNote: 'Completed, signed and dated' },
    { licenseName: 'BOOTH', itemNumber: 2, documentName: 'Floor Plan of the Arena/venue', responsibleEntity: 'Applicant', requirementNote: 'Service Area for liquor' },
    { licenseName: 'BOOTH', itemNumber: 3, documentName: 'Nominated Name of Publican, Holders of Tavern license', responsibleEntity: 'Applicant', requirementNote: 'Applicable if occasion will be held in an unlicensed premises (To provide service of alcohol on behalf of the organizers' },
    { licenseName: 'BOOTH', itemNumber: 4, documentName: "Written consent of other Venue's Management", responsibleEntity: 'Applicant', requirementNote: 'To be confirmed by way of Letter' },
    { licenseName: 'BOOTH', itemNumber: 5, documentName: 'Statutory Declaration Form', responsibleEntity: 'Justice of Peace', requirementNote: 'All information, material particular are true and correct.' },
    { licenseName: 'BOOTH', itemNumber: 6, documentName: 'Copy of official Receipt For Payment of License fees', responsibleEntity: 'NCDC', requirementNote: 'For reference' },
    { licenseName: 'BOOTH', itemNumber: 7, documentName: 'Land Tax & Garbage Bills', responsibleEntity: 'NCDC', requirementNote: 'Evidence' },
];

export const specialRequirementsData = [
    { licenseName: 'ELECTRONIC SHOP', requirementName: 'Radio communication Apparatus License', issuingAuthority: 'National Information and Technology Authority (NICTA)', description: 'For businesses using radio communication equipment' },
    { licenseName: 'PHARMACY', requirementName: 'Pharmaceutical License', issuingAuthority: 'NDoH-Pharmacy Board', description: 'Required for pharmacy operations' },
    { licenseName: 'SECOND HAND USED CLOTHING', requirementName: 'Certificate of Fumigation', issuingAuthority: 'National Department of Health (NDoH)', description: 'Required for second-hand clothing' },
    { licenseName: 'FUEL DISTRIBUTION/INDUSTRIAL GAS', requirementName: 'Inflammable & Dangerous Goods License/certificate', issuingAuthority: 'Labour Department', description: 'Required for fuel-related businesses' },
    { licenseName: 'FUEL STATION', requirementName: 'Inflammable & Dangerous Goods License/certificate', issuingAuthority: 'Labour Department', description: 'Required for fuel stations' },
    { licenseName: 'MECHANICAL WORKSHOP', requirementName: 'Factory/Manufacturer License', issuingAuthority: 'Labour Department', description: 'Required for manufacturing operations' },
    { licenseName: 'MANUFACTURER', requirementName: 'Factory/Manufacturer License', issuingAuthority: 'Labour Department', description: 'Required for manufacturing operations' },
    { licenseName: 'MANUFACTURER', requirementName: 'Food Safety Management System (HACCP)', issuingAuthority: 'Applicant', description: 'Required for food-related businesses' },
    { licenseName: 'TAVERN', requirementName: 'Food Safety Management System (HACCP)', issuingAuthority: 'Applicant', description: 'Required for food-related businesses' },
    { licenseName: 'LIMITED HOTEL', requirementName: 'Food Safety Management System (HACCP)', issuingAuthority: 'Applicant', description: 'Required for food-related businesses' },
    { licenseName: 'RESTAURANT', requirementName: 'Food Safety Management System (HACCP)', issuingAuthority: 'Applicant', description: 'Required for food-related businesses' },
    { licenseName: 'CANTEEN', requirementName: 'Food Safety Management System (HACCP)', issuingAuthority: 'Applicant', description: 'Required for food-related businesses' },
    { licenseName: 'PUBLICAN', requirementName: 'Food Safety Management System (HACCP)', issuingAuthority: 'Applicant', description: 'Required for food-related businesses' },
    { licenseName: 'MOTOR VEHICLE DEALER', requirementName: 'Motor Car Dealers License', issuingAuthority: 'Land Transport Board', description: 'Required for vehicle dealerships' },
    { licenseName: 'PACKET (LIQUOR)', requirementName: 'Certified Sea Going Vessel', issuingAuthority: 'National Maritime Safety Authority', description: 'Required for Packet liquor license' },
    { licenseName: 'PACKET (LIQUOR)', requirementName: 'Certified Overseas Ship', issuingAuthority: 'National Maritime Safety Authority', description: 'Required for Packet liquor license' }
];
